# Generated by Django 3.0.4 on 2020-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenSys', '0002_auto_20200326_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='empNum',
            field=models.CharField(max_length=6, unique=True, verbose_name='Employee ID '),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name '),
        ),
    ]
