# Generated by Django 3.0.4 on 2020-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenSys', '0004_auto_20200326_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='options',
            field=models.SmallIntegerField(choices=[(1, 'Veg w egg'), (2, 'Veg w/o egg'), (3, 'Non-Veg')], default=2, verbose_name='Food Style '),
        ),
    ]
