# Generated by Django 3.0.4 on 2020-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenSys', '0005_auto_20200326_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Item Name '),
        ),
    ]
