# Generated by Django 3.0.4 on 2020-03-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteenSys', '0006_auto_20200326_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_prepared',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_sheduled',
        ),
        migrations.AddField(
            model_name='order',
            name='additional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canteenSys.MenuItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
